# Generated by Django 5.2 on 2026-04-10 23:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('hostname', models.CharField(blank=True, max_length=150, null=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('asset_type', models.CharField(choices=[('SERVER', 'Server'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('FIREWALL', 'Firewall'), ('WORKSTATION', 'Workstation'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('UNSTABLE', 'Unstable'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('is_monitored', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
