# Generated by Django 5.2 on 2026-03-30 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('detection_rule', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('UNDER_ANALYSIS', 'Under analysis'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed')], default='NEW', max_length=20)),
                ('detected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='assets.asset')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='events.networkevent')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
