# Generated by Django 5.2 on 2026-04-10 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=20)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('packet_size', models.IntegerField(blank=True, null=True)),
                ('tcp_flags', models.CharField(blank=True, default='', max_length=50)),
                ('dns_query', models.CharField(blank=True, default='', max_length=255)),
                ('icmp_type', models.IntegerField(blank=True, null=True)),
                ('icmp_code', models.IntegerField(blank=True, null=True)),
                ('event_timestamp', models.DateTimeField()),
                ('raw_summary', models.TextField(blank=True, default='')),
                ('collector_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assets.asset')),
            ],
        ),
    ]
