# Generated by Django 5.2 on 2026-03-30 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('ICMP', 'ICMP'), ('TCP', 'TCP'), ('DNS', 'DNS')], max_length=10)),
                ('transport_layer', models.CharField(blank=True, max_length=20, null=True)),
                ('packet_size', models.PositiveIntegerField(blank=True, null=True)),
                ('tcp_flags', models.CharField(blank=True, max_length=20, null=True)),
                ('dns_query', models.CharField(blank=True, max_length=255, null=True)),
                ('icmp_type', models.PositiveIntegerField(blank=True, null=True)),
                ('icmp_code', models.PositiveIntegerField(blank=True, null=True)),
                ('event_timestamp', models.DateTimeField()),
                ('raw_summary', models.TextField(blank=True, null=True)),
                ('collector_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assets.asset')),
            ],
            options={
                'ordering': ['-event_timestamp'],
            },
        ),
    ]
